[package]
name = "Htrace"
version = "0.1.0"
authors = ["Hyultis <hyultis@use.startmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
anyhow = "1.0.86"
Hconfig = "1.0.0"
backtrace = "0.3.73"
dashmap = "6.0.1"
thiserror = "1.0.63"
strfmt = "0.2.4"
arc-swap = "1.7.1"
parking_lot = "0.12.3"
singletonThread = "1.0.0"
owo-colors = "4.0.0"
