[package]
name = "Htrace"
version = "0.1.0"
authors = ["Hyultis <hyultis@use.startmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.21"
anyhow = "1.0.51"
Hconfig = {git="ssh://git@github.com/hyultis/rust_Hconfig.git", branch = "master"}
backtrace = "0.3.67"
json = "0.12.4"
dashmap = "5.4.0"
thiserror = "1.0.40"
strfmt = "0.2.4"
arc-swap = "1.6.0"
parking_lot = "0.12.1"
