[package]
name = "Htrace"
version = "0.1.0"
authors = ["Hyultis <hyultis@use.startmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
chrono = "0.4.21"
anyhow = "1.0.51"
Hconfig = { path = "../Hconfig" }
backtrace = "0.3.66"
