[package]
name = "Htrace"
version = "2.0.0"
authors = ["Hyultis <hyultis@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hyultis/rust_Htrace"
keywords = ["tracing","trace","log","logging"]
categories = ["development-tools::debugging"]
description = "simple tracing system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version="0.3" , features = ["macros","formatting"]}
anyhow = "1.0"
#Hconfig = "1.1"
Hconfig = {  path="../Hconfig" }
backtrace = "0.3"
dashmap = "7.0.0-rc2"
thiserror = "2.0"
arc-swap = "1.7"
parking_lot = "0.12"
singletonThread = "1.1"
owo-colors = "4.2"
